services:
  server:
    build:
      context: .
    container_name: orbit
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - .:/var/www/html:cached
      - laravel_storage:/var/www/html/storage
      - laravel_cache:/var/www/html/bootstrap/cache

volumes:
  laravel_storage:
  laravel_cache:
